### PR TITLE
feat: containerize application

### PR DESCRIPTION
**Pull request by tamcore**
This PR will
- introduce a Dockerfile to build a container image for the app
  - based on official php:httpd container image (Debian based)
  - everything runs rootless (port 8080 for the webapp)
  - has options to override the default timezone, set the default language and automatically create an admin user
  - runs the required cronjob every 5 minutes (although I suppose we could make that adjustable as well, if you prefer)
- introduce a Github Workflow to directly build the container image, both as amd64 and arm64 images
  - either manually (gets tagged with `dev` then)
  - or when pushing a semver tag like `v0.0.1` (gets tagged with `latest` and `v0.0.1` then)

### CODE REVIEW

**Comment by eusonlito** [comment]
Let me review this implementation 😊

I'm using docker in some other projects like https://github.com/eusonlito/Password-Manager and I would like to do some similiar.

Regards!

**Comment by tamcore** [comment]
Ah, okay. Haven't seen that one 🙈 If you want me to change something, please let me know.

Actually had already started on this, right after your project introduction on Reddit, last year. Just couldn't make friends with composer 😂

**Comment by tamcore** [comment]
Please be careful with `php artisan serve --host=0.0.0.0 --port=80`, that's fine for development, but shouldn't be exposed to the internet, as that exposes your PHP unprotected instance, which is running with superuser privileges.

**Comment by eusonlito** [comment]
As far as I know, running php as root inside a docker instance is not a security issue per se, it all depends on the code you run. I'm missing something?

**Comment by tamcore** [comment]
https://www.php.net/manual/en/features.commandline.webserver.php

> This web server is designed to aid application development. It may also be useful for testing purposes or for application demonstrations that are run in controlled environments. It is not intended to be a full-featured web server. It should not be used on a public network.

**Comment by eusonlito** [comment]
Yes, I know, but I'm using the `php artisan serve` in a lot of projects without problem :)

Also, as almost docker environments, you must set a web server as reverse proxy to add full server web server features (ssl, domains, etc...) in front the container.

You can test the new (and hope finally) version :)

**Comment by tamcore** [comment]
I don't think I'll be able to run your version in production. And so probably shouldn't anybody else, as that's a security issue waiting to happen :(

* the integrated php webserver isn't supposed to be exposed to the internet (even upstream says so)
  * it even needlessly runs as a privileged user
* the container brings too many unneeded dependencies (`apt-utils`, `htop`, `vim`, `procps`, just to name a few)
  * there's also no cache managing for `/root/.composer` for example
* the `Dockerfile` references `composer:latest`. Referencing `latest` is bad practice.
* Running the entire thing with a permanent `memory_limit of 2G` also isn't the best idea

That's a development container, not ready for production use. Please look up some container guidelines by the NSA and the german BSI. 
Also, just comparing our images
```
$ docker image ls | grep gps-tracker
gps-tracker   yours      8d932efb1e79   12 minutes ago   938MB
gps-tracker   mine       d7f8b9eaa800   21 minutes ago   557MB
```
938MB is wayy to much. That's a looot of overhead, if one wants to run multiple replicas of it.

Running it through [aquasecurity/trivy](https://github.com/aquasecurity/trivy) also doesn't look good.

Screenshot 2023-02-10 at 08 15 58

**Comment by eusonlito** [comment]
Ok, I will work more on it based on yours recomendations.

Maybe the size are required dependencies that you aren't loaded? My additional dependencies are all some additional kb.

Anyway thanks for your work and help.

**Comment by eusonlito** [comment]
Finally:

```
docker image ls | grep gpstracker

gpstracker-app   latest    351eed5f424b   20 minutes ago   657MB
```
```
sudo trivy image gpstracker-app --ignore-unfixed

2023-02-11T19:27:01.241+0100	INFO	Vulnerability scanning is enabled
2023-02-11T19:27:01.241+0100	INFO	Secret scanning is enabled
2023-02-11T19:27:01.241+0100	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-02-11T19:27:01.241+0100	INFO	Please see also https://aquasecurity.github.io/trivy/v0.37/docs/secret/scanning/#recommendation for faster secret detection
2023-02-11T19:27:01.254+0100	INFO	Detected OS: debian
2023-02-11T19:27:01.254+0100	INFO	Detecting Debian vulnerabilities...
2023-02-11T19:27:01.283+0100	INFO	Number of language-specific files: 1
2023-02-11T19:27:01.283+0100	INFO	Detecting composer vulnerabilities...

gpstracker-app (debian 11.6)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

Thanks for your advices for the improvement of Docker integration.

**Pull request closed without merging**
